"""Generate the Cedar schema from the sensor registry (plan.md S2.2).

`policies/schema.cedarschema` is no longer hand-written. It is produced from
`agentguard.sensors`, so registering a predicate and regenerating is the whole
of "add a sensor" -- there is no second place to remember.

    make schema        regenerate policies/schema.cedarschema
    make validate      fails if the file on disk is not what this would produce

Two variants, because thesis §C.2 asks which one catches more real authoring
errors and that is a question with an answer rather than a preference:

    record   context.flags is a record of optional Bools, one per sensor
    set      context.flags is a Set<String> of the names that fired

`record` is the default, on the evidence from S1.3: under `Set<String>` any
string is a valid member, so `contains("involve_system_fyle")` type-checks and
the policy silently never fires. Under a record the attribute does not exist and
validation fails, naming the typo.

Why the Bools are **optional** (`name?: Bool`) rather than required
------------------------------------------------------------------
Measured, not assumed (see tests/test_schema_codegen.py):

  * With **required** attributes a request must carry every declared flag, or
    Cedar answers `NoDecision`. Since the engine only runs the sensors that
    apply to the domain at hand (S2.1: five embodied sensors *raise* on a code
    agent's trace), satisfying that means sending `false` for sensors that never
    ran. That is precisely the failure this project exists to remove: a safety
    flag reading "the dangerous thing is not happening" when nobody looked.

  * With **optional** attributes the request carries exactly the sensors that
    were evaluated, and Cedar refuses to validate an unguarded access --
    "unable to guarantee safety of access". So a policy is *forced* to spell out
    `context.flags has X && context.flags.X`, and the three states stay
    distinct:

        has X && X       evaluated, fired
        has X && !X      evaluated, did not fire
        !(has X)         never evaluated

The verbosity is the honesty. It is also mechanical, so S3.3's compiler emits it
rather than a human writing it.
"""
import os
import re

import agentguard
from agentguard import sensors

SCHEMA_PATH = os.path.join(agentguard.POLICY_DIR, "schema.cedarschema")

#: context.flags as a record of optional Bools, one attribute per sensor.
RECORD = "record"
#: context.flags as an open Set<String> of the names that fired.
SET = "set"
VARIANTS = (RECORD, SET)
DEFAULT_VARIANT = RECORD

#: Written into the generated header so the request builder can read back which
#: shape the file on disk actually uses, rather than being told separately and
#: risking the two disagreeing.
VARIANT_MARKER = "@flags-variant"
_VARIANT_RE = re.compile(rf"{re.escape(VARIANT_MARKER)}\s+(\w+)")

NAMESPACE = "AgentGuard"

_HEADER = """\
// AgentGuard -- the Cedar schema for AgentSpec's guard decisions.
//
// GENERATED by agentguard/schema.py from the sensor registry. Do not edit by
// hand: `make schema` overwrites it. To add a flag, register the predicate in
// rules.manual.table and regenerate (plan.md S2.2).
//
// {VARIANT_MARKER} {variant}
//
// This file is the contract between the two halves of the architecture:
//
//   Python side   sensors run the AgentSpec predicates over user_input,
//                 tool_input and intermediate_steps. Impure, arbitrary code.
//   Cedar side    a decision over the *result* of that work. Pure and total --
//                 no regex, no AST walking, no I/O.
//
// The schema is what makes the second half checkable. Every policy is validated
// against it before the agent takes a step, so the failure modes recorded in
// tests/test_fail_open.py -- a rule that loads fine and then never fires, or
// crashes mid-run -- become load-time errors instead.
//
// Deliberately smaller than the thesis design (plan C.2). Deferred, with the step
// that adds it:
//
//   Session entity + Agent.session   S4.2   path sensitivity (taints, approvals)
//   Agent.autonomy, Agent.model      S2.7   escalation policies need them
//   Tool.name                        S2.7   the uid carries it for now
//   context.targets / risk / step    S4.2   resolved paths and hosts
//   action finish                    S2.7   `trigger finish` rules
"""

#: Written at the same indent as `flags:` itself. A generated file still has to
#: explain itself -- more so, since nobody edits it and reads the reasoning there.
_FLAGS_DOC = {
    RECORD: """\
// One optional Bool per registered sensor ({count}). Optional is load-bearing:
// the request carries only the sensors that actually ran, and Cedar refuses to
// validate an unguarded access -- so a policy must write
// `context.flags has X && context.flags.X`, and cannot confuse "evaluated and
// false" with "never run".""",
    SET: """\
// The names of the sensors that fired. Open: any string is a valid member, so
// the validator cannot catch a misspelled flag, and such a policy silently
// never fires (S1.3). Generatable only for the C.2 comparison -- the engine is
// not meant to ship on this variant.""",
}

_BODY = """
namespace {namespace} {{

  // The agent being guarded. One per run.
  entity Agent = {{
    framework: String,          // "langchain" -- the only binding wired up so far
  }};

  // The tool it is proposing to invoke. The uid is AgentSpec's tool name, so
  // `trigger python_repl` compiles to resource == Tool::"python_repl".
  entity Tool = {{
    kind: String,               // "code_exec" | "shell" | "http" | "actuator" | "read_only"
    reversible: Bool,           // can the effect be undone?
  }};

  // One proposed tool call. The AgentSpec `check` clause lands in context.flags.
  action invoke appliesTo {{
    principal: [Agent],
    resource:  [Tool],
    context: {{
{flags}
    }}
  }};
}}
"""


def flags_block(variant=DEFAULT_VARIANT, flags=None):
    """The `flags:` declaration for one variant, indented for the context block."""
    if variant not in VARIANTS:
        raise ValueError(f"unknown flags variant {variant!r}; expected one of {VARIANTS}")
    flags = tuple(sorted(sensors.FLAGS if flags is None else flags))

    doc = "\n".join(
        "      " + line
        for line in _FLAGS_DOC[variant].format(count=len(flags)).splitlines()
    )

    if variant == SET:
        return f"{doc}\n      flags: Set<String>,"

    # Trailing comma on every line but the last: Cedar accepts no trailing comma
    # inside a record type.
    entries = ",\n".join(f"        {flag}?: Bool" for flag in flags)
    return f"{doc}\n      flags: {{\n{entries}\n      }},"


def generate(variant=DEFAULT_VARIANT, flags=None):
    """The full schema text. Deterministic: same registry in, same bytes out.

    Determinism is the point -- it is what lets `make validate` assert that the
    file on disk is still what the registry says it should be. A timestamp in
    the header would make every regeneration a diff and that check worthless.
    """
    header = _HEADER.format(VARIANT_MARKER=VARIANT_MARKER, variant=variant)
    return header + _BODY.format(namespace=NAMESPACE,
                                 flags=flags_block(variant, flags))


def variant_of(text):
    """Which variant a schema file was generated with.

    Read from the file rather than configured separately, so the request builder
    and the schema on disk cannot drift apart.
    """
    found = _VARIANT_RE.search(text)
    if not found or found.group(1) not in VARIANTS:
        raise ValueError(
            f"schema has no readable {VARIANT_MARKER} marker -- regenerate it "
            "with `make schema`"
        )
    return found.group(1)


def read_variant(path=SCHEMA_PATH):
    with open(path, encoding="utf-8") as handle:
        return variant_of(handle.read())


def is_current(path=SCHEMA_PATH):
    """(ok, reason) -- does the file on disk match what the registry produces?"""
    try:
        with open(path, encoding="utf-8") as handle:
            on_disk = handle.read()
    except OSError as exc:
        return False, str(exc)
    try:
        variant = variant_of(on_disk)
    except ValueError as exc:
        return False, str(exc)
    if on_disk != generate(variant):
        return False, (f"stale or hand-edited: does not match agentguard/schema.py "
                       f"over {len(sensors.FLAGS)} sensors -- run `make schema`")
    return True, ""


def write(path=SCHEMA_PATH, variant=DEFAULT_VARIANT):
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(generate(variant))
    return path


def _main(argv=None):
    import argparse                                    # noqa: PLC0415

    parser = argparse.ArgumentParser(description="regenerate the Cedar schema")
    parser.add_argument("--variant", choices=VARIANTS, default=DEFAULT_VARIANT)
    parser.add_argument("--stdout", action="store_true",
                        help="print instead of writing the file")
    parser.add_argument("--path", default=SCHEMA_PATH)
    args = parser.parse_args(argv)

    if args.stdout:
        print(generate(args.variant), end="")
        return 0
    write(args.path, args.variant)
    print(f"wrote {os.path.relpath(args.path, agentguard.REPO_ROOT)} "
          f"({args.variant}, {len(sensors.FLAGS)} flags)")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
