#!/usr/bin/env python3
"""Compile the whole rule corpus into `policies/generated/` (plan.md S3.4).

    make compile-corpus

Writes one **self-contained policy directory per domain**, because an engine
runs one domain's sensors (S2.3) and refuses to start on a policy keyed on a
flag it will never materialise (S2.5). The whole corpus in one file does not
load, and should not:

    policies/generated/code/       schema + the code-domain rules
    policies/generated/embodied/   schema + the embodied rules
    policies/generated/llm/        schema + the LLM-generated rules
    policies/generated/coverage.json

Each directory holds its own `schema.cedarschema` and a baseline `permit`, so it
is loadable as-is:

    AGENTGUARD_POLICIES=policies/generated/code AGENTGUARD=cedar ...

The LLM directory has a **wider schema**. Those rules carry the source of their
own predicates, so they define flags the registry does not have; the schema
generator takes the extra names and declares them. Nothing here executes that
source -- the function names come from `ast.parse`. Registering them for real,
so an engine could actually materialise them, is a separate decision.
"""
import argparse
import collections
import json
import os
import shutil
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from agentguard import compile as ag_compile          # noqa: E402
from agentguard import schema as ag_schema            # noqa: E402
from agentguard import sensors as sensor_registry     # noqa: E402

GENERATED = os.path.join(REPO_ROOT, "policies", "generated")

BASELINE = """\
@id("baseline_allow_tools")
permit (
  principal,
  action == AgentGuard::Action::"invoke",
  resource
);
"""

HEADER = """\
// GENERATED by tools/compile_corpus.py from the AgentSpec rule corpus.
// Do not edit: `make compile-corpus` overwrites this file.
//
// {count} rules compiled into this domain ({domain}).
// Every policy carries @source naming the rule it came from.
//
// The rules that did *not* compile, and why, are in policies/generated/
// coverage.json and docs/coverage.md -- they are the RQ1 result, not debris.
{note}"""

#: The LLM directory validates but cannot be *loaded*. Saying so in the file
#: matters: "it type-checks" and "an engine will run it" are different claims,
#: and the gap between them is what the S2.5 coverage check exists to catch.
LLM_NOTE = """\
//
// !! THIS DIRECTORY VALIDATES BUT WILL NOT LOAD.
//
// These rules bring the source of their own predicates, so the schema beside
// them declares flags the sensor registry does not have. Cedar is satisfied --
// the attributes exist. The engine is not: agentguard.engine.load refuses a
// policy keyed on a flag no *sensor* will ever materialise, and none of these
// has one.
//
// Declaring a flag is not the same as being able to observe it. To deploy these,
// register their predicates in agentguard/sensors.py first -- which means
// deciding to run model-written Python, a decision nothing here makes for you.
// Nothing in this toolchain has executed that source: the predicate names come
// from ast.parse.
"""


def corpus_files():
    import glob                                        # noqa: PLC0415

    files = sorted(glob.glob(os.path.join(REPO_ROOT, "src/rules/**/*.ar"),
                             recursive=True))
    files += sorted(glob.glob(os.path.join(REPO_ROOT, "src/rules/**/*.rule"),
                              recursive=True))
    return files


def llm_files():
    import glob                                        # noqa: PLC0415

    return sorted(glob.glob(os.path.join(REPO_ROOT,
                                         "src/rules/llm/generated_rules-*.jsonl")))


def write_domain(directory, policies, schema_text, domain, count, note=""):
    os.makedirs(directory, exist_ok=True)
    with open(os.path.join(directory, "schema.cedarschema"), "w",
              encoding="utf-8", newline="\n") as handle:
        handle.write(schema_text)
    with open(os.path.join(directory, "rules.cedar"), "w",
              encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER.format(count=count, domain=domain, note=note))
        handle.write("\n" + BASELINE)
        for policy in policies:
            handle.write("\n" + policy)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    shipped = [c for path in corpus_files() for c in ag_compile.compile_file(path)]

    extra = ag_compile.llm_flags(llm_files())
    llm = [c for path in llm_files() for c in ag_compile.compile_llm_file(path)]

    if os.path.isdir(GENERATED):
        shutil.rmtree(GENERATED)
    os.makedirs(GENERATED)

    base_schema = ag_schema.generate()
    written = {}

    for domain in ("code", "embodied"):
        # A rule reading no flags at all fits either domain, so it goes in both.
        chosen = [c for c in shipped if c.ok and c.domain in (domain, None)]
        write_domain(os.path.join(GENERATED, domain),
                     [c.policy for c in chosen], base_schema, domain, len(chosen))
        written[domain] = [c.rule_id for c in chosen]

    llm_schema = ag_schema.generate(
        flags=tuple(sorted(set(sensor_registry.FLAGS) | set(extra))))
    chosen = [c for c in llm if c.ok]
    write_domain(os.path.join(GENERATED, "llm"), [c.policy for c in chosen],
                 llm_schema, "llm / embodied", len(chosen), note=LLM_NOTE)
    written["llm"] = [c.rule_id for c in chosen]

    coverage = {
        "shipped": summarise(shipped),
        "llm": summarise(llm),
        "llm_flags_defined": list(extra),
        "written": {k: len(v) for k, v in written.items()},
    }
    with open(os.path.join(GENERATED, "coverage.json"), "w",
              encoding="utf-8", newline="\n") as handle:
        json.dump(coverage, handle, indent=2, sort_keys=True)
        handle.write("\n")

    if not args.quiet:
        report(shipped, llm, extra, written)
    return 0


def summarise(results):
    reasons = collections.Counter()
    for compiled in results:
        for reason in compiled.reasons:
            reasons[reason.split(" -- ")[0].split(",")[0][:70]] += 1
    return {
        "total": len(results),
        "compiled": sum(1 for c in results if c.ok),
        "rules": [
            {"id": c.rule_id, "source": c.source, "ok": c.ok,
             "domain": c.domain, "reasons": list(c.reasons),
             "warnings": list(c.warnings)}
            for c in results
        ],
        "reason_counts": dict(reasons.most_common()),
    }


def report(shipped, llm, extra, written):
    ok = sum(1 for c in shipped if c.ok)
    print(f"shipped corpus : {ok}/{len(shipped)} rules compiled")
    print(f"LLM-generated  : {sum(1 for c in llm if c.ok)}/{len(llm)} rules compiled "
          f"({len(extra)} predicates they define themselves)")
    print()
    for name, ids in sorted(written.items()):
        rel = os.path.join("policies", "generated", name).replace(os.sep, "/")
        print(f"  {rel + '/':34s} {len(ids)} policies")
    print(f"\n  policies/generated/coverage.json   every rule, with its reasons")


if __name__ == "__main__":
    raise SystemExit(main())
