#!/usr/bin/env python3
"""Turn policies/generated/coverage.json into docs/coverage.md (plan.md S3.5).

    make coverage-freeze

This is RQ1: *how much of the existing rule corpus comes across?* The prose
lives here rather than in the Markdown so that regenerating cannot leave the
analysis disagreeing with the numbers it describes.
"""
import argparse
import collections
import datetime
import json
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COVERAGE = os.path.join(REPO_ROOT, "policies", "generated", "coverage.json")

#: reason prefix -> the category it belongs to, and how to read that category.
CATEGORIES = [
    ("no registered sensor produces", "unregistered predicate"),
    ("parameterised predicate", "parameterised predicate"),
    ("triggers on", "non-invoke trigger"),
    ("enforcement is", "config enforcement"),
    ("does not parse", "does not parse"),
    ("`enforce none`", "enforce none"),
    ("names several enforcements", "ambiguous enforcement"),
]

EXPLANATIONS = {
    "unregistered predicate": (
        "The rule names a predicate that no sensor produces. **These rules "
        "cannot fire in AgentSpec either** -- `RuleInterpreter.eval_predicate` "
        "does `predicate_table[name]` and raises `KeyError` mid-run. This is "
        "not a limit of the target language; it is the corpus and its registry "
        "having drifted apart (docs/findings.md D-3)."),
    "parameterised predicate": (
        "`v_f_disL(10)` -- a predicate with an argument. Our sensors are "
        "nullary: a sensor produces a named flag, and a flag has no parameters. "
        "This *is* a limit of the design, and a real one; see the ladder below "
        "for what lifting it would buy."),
    "non-invoke trigger": (
        "`trigger state_change` -- the rule fires on a world-state change "
        "rather than a tool call. The schema declares one action, `invoke`. "
        "Adding `action state_change` is straightforward, and on its own it "
        "would rescue nothing: every rule in this group is blocked by at least "
        "one other cause as well."),
    "config enforcement": (
        "`real:obstacle:Min_stop_distance = 10` -- the enforcement assigns a "
        "planner parameter rather than permitting or forbidding an action. "
        "Cedar has no equivalent and should not: this is not access control, it "
        "is configuration. Arguably these rules are out of scope for a guard "
        "entirely."),
    "does not parse": (
        "One rule's check clause is an English sentence "
        "(docs/findings.md D-9). Accepting it would mean accepting arbitrary "
        "prose."),
    "enforce none": (
        "The rule matches and then chooses not to act, so there is nothing to "
        "forbid."),
    "ambiguous enforcement": (
        "Several enforcements in one clause. Which applies is undefined in "
        "AgentSpec too -- the interpreter looks the whole clause text up as a "
        "single key."),
}


def category(reason):
    for prefix, name in CATEGORIES:
        if reason.startswith(prefix):
            return name
    return f"other: {reason[:40]}"


def categories_of(rule):
    return {category(r) for r in rule["reasons"]}


def ranked(counter):
    """Counter.most_common(), but with ties broken by name.

    `categories_of` returns a set, and set iteration order for strings varies
    between processes, so `most_common()` alone ordered equal counts
    differently on every run -- a generated document that changed without its
    input changing. tests/test_compile.py catches it.
    """
    return sorted(counter.items(), key=lambda kv: (-kv[1], sorted(kv[0])))


def provenance():
    def git(*args):
        try:
            return subprocess.run(("git", "-C", REPO_ROOT) + args,
                                  capture_output=True, text=True,
                                  check=True).stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            return "unknown"

    return "\n".join([
        "# Rule-corpus coverage — RQ1",
        "",
        "> Generated by `tools/coverage_report.py` from",
        "> `policies/generated/coverage.json`. Regenerate with `make coverage-freeze`.",
        "",
        "| | |",
        "|---|---|",
        f"| generated | {datetime.date.today().isoformat()} |",
        f"| commit | `{git('rev-parse', 'HEAD')}` |",
        f"| compiler | `agentguard/compile.py` (S3.3) |",
        f"| grammar | `agentguard/speclang/AgentSpecFull.g4` (S3.1) |",
        "",
    ])


def headline(shipped, llm):
    ok = shipped["compiled"]
    total = shipped["total"]
    clean = sum(1 for r in shipped["rules"] if r["ok"] and not r["warnings"])
    warned = ok - clean
    return "\n".join([
        "## The number",
        "",
        f"**{ok} of {total} shipped rules compile into Cedar policies "
        f"({100 * ok / total:.0f}%).**",
        "",
        "| | rules |",
        "|---|---:|",
        f"| compiled cleanly | **{clean}** |",
        f"| compiled with warnings | {warned} |",
        f"| did not compile | {total - ok} |",
        f"| **total** | **{total}** |",
        "",
        "The bare percentage is the least interesting number on this page. The "
        f"{total - ok} failures are not one problem, and only one of the five "
        "causes below is a limit of what Cedar can express. The largest is a "
        "corpus that names detectors nobody ever wrote — rules that could not "
        "fire in AgentSpec either.",
        "",
        f"For contrast, the {llm['total']} LLM-generated rules in "
        f"`src/rules/llm/generated_rules-*.jsonl` compile at "
        f"**{llm['compiled']}/{llm['total']}** — see *The other corpus* below.",
        "",
    ])


def by_cause(shipped):
    fails = [r for r in shipped["rules"] if not r["ok"]]
    counts = collections.Counter(c for r in fails for c in categories_of(r))
    multi = sum(1 for r in fails if len(categories_of(r)) > 1)
    lines = [
        "## Why the rest did not — every failure, by cause",
        "",
        "A rule can be blocked by several things at once, so these sum to more "
        f"than {len(fails)}. That is deliberate: **{multi} of the {len(fails)} "
        "are blocked by more than one independent cause**, and a table counting "
        "only the first cause per rule would make the remaining work look "
        "smaller than it is.",
        "",
        "| cause | rules |",
        "|---|---:|",
    ]
    for name, n in ranked(counts):
        lines.append(f"| {name} | {n} |")
    lines += ["", "### What each one means", ""]
    for name, _n in ranked(counts):
        lines += [f"**{name}** — {EXPLANATIONS.get(name, '')}", ""]
    return "\n".join(lines)


def groups(shipped):
    """The failing rules partitioned by their *complete* set of blockers.

    This is the shape of the result, and it is not a long tail: 44 failures
    fall into four groups, and no rule sits between them.
    """
    fails = [r for r in shipped["rules"] if not r["ok"]]
    counted = collections.Counter(
        frozenset(categories_of(r)) for r in fails)
    lines = [
        "## The failures partition — they are not a long tail",
        "",
        "Every failing rule is counted here against the *complete* set of "
        "causes blocking it. There is no long tail and no partial credit: the "
        f"{len(fails)} failures fall into four groups and nothing sits between "
        "them.",
        "",
        "| rules | blocked by | to rescue them |",
        "|---:|---|---|",
    ]
    fixes = {1: "one change", 2: "both changes, together",
             3: "all three changes, together"}
    for combo, n in ranked(counted):
        if combo == {"does not parse"}:
            need = "nothing — it is prose, not a rule"
        elif combo == {"unregistered predicate"}:
            need = "one change (but 23 detectors to write)"
        else:
            need = fixes.get(len(combo), "—")
        lines.append(f"| **{n}** | {', '.join(sorted(combo))} | {need} |")
    lines += [
        "",
        "The second column is why the ladder below has rows that rescue "
        "nothing. A rule blocked three times is not three-quarters of the way "
        "to compiling; it compiles when the last of the three lands, and not "
        "before.",
        "",
    ]
    return "\n".join(lines)


def ladder(shipped):
    fails = [r for r in shipped["rules"] if not r["ok"]]
    ok = shipped["compiled"]

    def rescued(allowed):
        return sum(1 for r in fails if categories_of(r) <= allowed)

    unreg = {"unregistered predicate"}
    both = unreg | {"non-invoke trigger"}
    three = both | {"parameterised predicate"}
    four = three | {"config enforcement"}
    total = shipped["total"]
    only_unreg = len([r for r in fails if categories_of(r) == unreg])
    apollo = rescued(four) - rescued(three)

    # Asserted from the data rather than from memory: the group that needs all
    # three changes is exactly the apollo corpus, and it is all of it.
    group = [r for r in fails if categories_of(r) <= four
             and not categories_of(r) <= three]
    all_apollo = all("/apollo/" in r["source"] for r in group)
    whole_family = len(group) == sum(1 for r in shipped["rules"]
                                     if "/apollo/" in r["source"])
    family = ("the apollo corpus, in its entirety"
              if all_apollo and whole_family else "one group")
    triples = sum(1 for r in group if len(categories_of(r)) == 3)

    return "\n".join([
        "## What would raise the number",
        "",
        "Cumulative: each row assumes every row above it. The last column is "
        "where the corpus would land.",
        "",
        "| change | rescues | coverage |",
        "|---|---:|---:|",
        f"| *(today)* | — | **{ok}/{total}** |",
        f"| write the {only_unreg} predicates the corpus names but never "
        f"registers | +{rescued(unreg)} | **{ok + rescued(unreg)}/{total}** |",
        f"| also add `action state_change` to the schema | +"
        f"{rescued(both) - rescued(unreg)} | {ok + rescued(both)}/{total} |",
        f"| also support parameterised sensors | +"
        f"{rescued(three) - rescued(both)} | {ok + rescued(three)}/{total} |",
        f"| also express planner-parameter assignment | +{apollo} | "
        f"**{ok + rescued(four)}/{total}** |",
        "",
        "**The two middle rows rescue nothing at all, and that is the "
        "finding.** Adding `action state_change` to the schema is an "
        "afternoon's work, and on its own it moves the number by zero: every "
        "rule that needs it also needs planner-parameter assignment, which is "
        f"the row that should not be implemented. Those {apollo} rules are "
        "all-or-nothing, and the 'all' includes a change this design should "
        "refuse.",
        "",
        "Read the table as three claims:",
        "",
        f"1. **{ok + rescued(unreg)}/{total} is the honest ceiling for the "
        "corpus as it stands.** The largest single cause of failure is the "
        "corpus naming predicates nothing registers — rules that were already "
        "dead in AgentSpec, since the interpreter raises `KeyError` on them "
        "mid-run. Writing those predicates is not a Cedar problem; the identical "
        "work would be needed to make AgentSpec itself run them. It is also the "
        "only row here that is purely labour: no design question, just 23 "
        "detectors nobody wrote.",
        "",
        f"2. **The last row is {family}, and it is asking for a different "
        f"tool.** All {apollo} of those rules trigger on world-state changes "
        f"and enforce by assigning planner parameters; {triples} of them also "
        "test parameterised predicates. Assignment — "
        "`real:obstacle:Min_stop_distance = 10` — is the blocker that matters, "
        "and it is not access control in any form: it neither permits nor "
        "forbids anything, it tunes a controller. Supporting it would mean "
        "deciding that a guardrail language should also be a configuration "
        "language. That is a design question rather than an implementation "
        "gap, and this project answers it 'no', which makes **the realistic "
        f"target {ok + rescued(unreg)}/{total} rather than "
        f"{ok + rescued(four)}/{total}.**",
        "",
        "3. **One rule can never compile**, because its check clause is an "
        "English sentence (D-9).",
        "",
    ])


def other_corpus(shipped, llm, flags):
    ok, total = shipped["compiled"], shipped["total"]
    return "\n".join([
        "## The other corpus, and what the contrast shows",
        "",
        "| corpus | rules | compile |",
        "|---|---:|---:|",
        f"| shipped `.ar` / `.rule` | {total} | {ok} ({100 * ok / total:.0f}%) |",
        f"| LLM-generated | {llm['total']} | **{llm['compiled']} "
        f"({100 * llm['compiled'] / llm['total']:.0f}%)** |",
        f"| LLM-generated, *not* counting the {len(flags)} predicates they "
        f"define themselves | {llm['total']} | **0** |",
        "",
        "Same compiler. The generated rules compile because each record carries "
        "the Python source of its own predicates; the hand-written corpus mostly "
        "does not because it names predicates that live somewhere else, or "
        "nowhere.",
        "",
        "**This is not evidence that a model writes better guardrails than a "
        "person.** The generated rules were produced together with their "
        "detectors, so they cannot drift from them; the hand-written corpus was "
        "not, and did. It is an argument about how a rule language should be "
        "packaged, not about who wrote the rules.",
        "",
        "It also does not mean those 20 policies are usable. "
        "`policies/generated/llm/` validates and **will not load**: the schema "
        "beside it declares the flags, but no sensor produces them, and the "
        "engine refuses a policy it could never fire. Deploying them would mean "
        "registering model-written Python as sensors.",
        "",
    ])


def per_file(shipped, written):
    per = collections.OrderedDict()
    for rule in shipped["rules"]:
        path = rule["source"].split("#")[0].replace("agentspec:", "")
        entry = per.setdefault(path, [0, 0])
        entry[0] += 1
        entry[1] += 1 if rule["ok"] else 0
    lines = ["## By file", "", "| file | rules | compiled |", "|---|---:|---:|"]
    for path, (total, ok) in per.items():
        lines.append(f"| `{path}` | {total} | {ok} |")

    code, embodied = written["code"], written["embodied"]
    both = code + embodied - shipped["compiled"]
    lines += [
        "",
        "The split is clean along the manual/apollo line, and it is not a "
        "coincidence: the three `manual/` files were written against a "
        "predicate registry, and the nine apollo files were written against a "
        "driving simulator.",
        "",
        f"Those {shipped['compiled']} policies are emitted as "
        f"**{code} into `policies/generated/code/` and {embodied} into "
        f"`policies/generated/embodied/`**, which sums to more than "
        f"{shipped['compiled']} because {both} of them read no domain-specific "
        "flag at all and so belong in both. One engine runs one domain's "
        "sensors (S2.3), so each directory has to stand alone.",
        "",
    ]
    return "\n".join(lines)


def appendix(shipped):
    lines = [
        "## Appendix — every rule",
        "",
        "Complete, because *\"an analysis of every failure\"* means every one.",
        "",
        "| rule | file | compiled | why not |",
        "|---|---|---|---|",
    ]
    for rule in shipped["rules"]:
        path = rule["source"].split("#")[0].replace("agentspec:src/rules/", "")
        mark = "yes" if rule["ok"] else "no"
        why = "" if rule["ok"] else "; ".join(rule["reasons"])
        why = why.replace("|", "\\|")
        lines.append(f"| `{rule['id']}` | `{path}` | {mark} | {why} |")
    return "\n".join(lines) + "\n"


def threats():
    return """\
## Threats to this number

* **It counts rules, not coverage of risk.** A corpus of 62 rules where 18
  compile says nothing about whether those 18 are the important ones. RQ2 and
  RQ3 measure that; this does not.
* **Whole-file parsing is a stricter measure and is not used here.** Two corpus
  files contain unmarked prose between rules (D-8), so no grammar parses them
  end to end. Splitting on `rule @` is how a compiler reads them, and how this
  is counted.
* **The compiler was written against this corpus.** It handles `act` prefixes
  and `llm_self_examine` because this corpus contains them. A different corpus
  would find different gaps, and the number would move.
* **Compiling is not enforcing.** A compiled policy still needs sensors that
  produce its flags. The 18 do; the 20 LLM ones do not.
"""


def build(coverage):
    shipped, llm = coverage["shipped"], coverage["llm"]
    return "\n".join([
        provenance(),
        headline(shipped, llm),
        by_cause(shipped),
        groups(shipped),
        ladder(shipped),
        other_corpus(shipped, llm, coverage["llm_flags_defined"]),
        per_file(shipped, coverage["written"]),
        appendix(shipped),
        threats(),
    ])


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--coverage", default=COVERAGE)
    args = parser.parse_args(argv)

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):                # pragma: no cover
        pass

    if not os.path.isfile(args.coverage):
        print(f"{args.coverage} is missing -- run `make compile-corpus` first",
              file=sys.stderr)
        return 1
    with open(args.coverage, encoding="utf-8") as handle:
        print(build(json.load(handle)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
